server:
  port: 8080

spring:
  application:
    name: community
  profiles:
    active: dev
  datasource:
      driver-class-name: ${community.datasource.driver-class-name}
      url: jdbc:mysql://${community.datasource.host}:${community.datasource.port}/${community.datasource.database}?serverTimezone=UTC
      username: ${community.datasource.username}
      password: ${community.datasource.password}
  data:
    redis:
      host: ${community.data.redis.host}
      port: ${community.data.redis.port}
      database: ${community.data.redis.database}

gitee:
  client:
    id: ${community.gitee.client-id}
    secret: ${community.gitee.client-secret}
  redirect:
    uri: ${community.gitee.redirect-url}
  grant:
    type: ${community.gitee.grant-type}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: codingforlove.community.model
  mapper-locations: classpath:mapper/*.xml

